mail.host=smtp.qq.com
mail.port=465
mail.username=3210559923@qq.com
mail.password=xbrgglvitwardchf
mail.protocol=smtps
mail.auth=true
mail.ssl.enable=true
mail.from=3210559923@qq.com
mail.from.name=校园公告系统